feat: 🎉 Add plugin admin settings page under the Settings Menu in the Dashboard
ucsc/ucsc-custom-functionality pull request #25
Opened 2024-06-12 22:46 UTC by Herm71

## Overview

This change adds a "plugin settings" page under the **Settings** menu in the WordPress Dashboard. The rationale for this addition is described in Issue #15. Fixes #15.

This PR scaffolds a page for future customized settings, if necessary; but also allows us to output the plugin's `version number` and include some additional details about the plugin. As described in the associated issue, CampusPress does not output version numbers for plugins or themes. This gives us an easy place to check, if we're working in WordPress.

## Testing

These changes were successfully tested by creating a  `.zip` file and uploading to an external staging site.

## Changes

Adds a link to the page from the plugin on the Plugins page:
(Note: screenshot from local dev, which does show version no.)

![info-link](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/32a91f58-a04c-469f-a477-92e64f5cb737)

Adds a new menu item under the Settings menu in the Dashboard:

![info-menu-item](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/99dafee4-10f5-4b36-8acf-cb6c5bd550f9)

Provides a basic "settings" page that is mainly used for information but can be expanded on as future needs arise:

![info-page](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/f7fcac63-bb02-4ff7-8e1e-4e775742a6a5)

2024-06-14 16:59 UTC, knice requested changes
Looks good! Three things:

1. Let's remove "info" from the admin menu link text. I know the admin page only contains information at the moment, but I think the long-term goal is to have actual settings.
2. Can you use `$plugin_data['Description']` for the description paragraph instead of hard-coded text? 
3. Add a link to the [Github releases page](https://github.com/ucsc/ucsc-custom-functionality/releases) in parenthesis after the version number.

Example: Version: 1.6.0 ([release notes](https://github.com/ucsc/ucsc-custom-functionality/releases))

2024-06-14 20:26 UTC, Herm71 commented
@knice Try it now?

2024-06-16 18:14 UTC, Herm71 commented
Requested changes:

- Remove link to page from Plugin
![no-link](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/a0e7b2b5-4dd1-42d1-85b2-a6dea71a8d49)
- Edit menu label
![menu-item](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/76898407-44cd-4caa-be0b-62ea4254dedd)

- Use `$plugin_data['Description']` and link to release notes
![functionality-info](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/6210b8e9-8782-446c-9920-2de18256426f)

2024-06-18 18:22 UTC, knice requested changes
Add a features list below the text description.

- Add Google Analytics 4 and Siteimprove scripts to the bottom of every page
- (short codes and descriptions)
- etc

2024-06-19 16:38 UTC, Herm71 commented
### Changes requested: 

I added some copy to the settings page and a list of "features." When I did that I noticed that there were _no styles_! Not even from the `user agent stylesheet`. So I created a stylesheet with some basic styles. It enqueues _only_ on the Settings page.

**Before styles:**
![settings-no-styles](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/89105d66-bc16-44b5-a8a9-24610812ced7)

**After styles:**
![settings-styles](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/82ec9d31-89a7-47a4-8435-2dab1a2b547d)

2024-06-20 17:13 UTC, knice commented
"Displays the last modified date of a page"

2024-06-20 17:29 UTC, knice requested changes
1. Change "returns" to "displays"
2. Remove "in the site footer" from the last modified short code description
3. Don't capitalize "last" in "Last modified"

2024-06-20 18:42 UTC, Herm71 commented
### Requested changes:
![newest](https://github.com/ucsc/ucsc-custom-functionality/assets/1000543/cce61e85-15bd-4bbc-b5aa-f32463702088)

2024-06-22 00:43 UTC, knice requested changes
It looks like you don't need to set a font-family on the admin dashboard. You've got `roboto` set in your stylesheet, but I can see the following default font-family is loaded on the body tag for all admin pages:

````css
font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
````   

I prefer we use defaults as much as possible.

2024-06-24 03:01 UTC, knice approved these changes
Looks great! 🥳

2024-06-24 11:09 UTC, merged